# Docker build file to create an image with centos 7
FROM centos:7
MAINTAINER andreas-bok-sociomantic <andreas.bok@sociomantic.com>

# install required packages
RUN yum install -y deltarpm && \
yum install -y rpm-build zlib-devel libtool openssl \
    openssl-devel automake autoconf gcc-c++
