#!/bin/sh
#
# script using fpm <https://github.com/jordansissel/fpm> to build libdrizzle-redux
# runtime, debugging and development deb packages
#
# Usage: ./build [package-name]
#
#     package-name        the name of the package to build

# function to display usage
usage()
{
    cat << EOF
The script is using fpm <https://github.com/jordansissel/fpm> to build
libdrizzle-redux runtime, debugging and development deb packages

    Usage: ./build [package-name]

    package-name    the name of the package to build
    -h, --help      display this help and exit
EOF
}

set -e

# check cmd arguments
if [ -z "$1" ]; then
    echo "Expected package name as first argument"
    usage
    exit 1
elif [ $1 = "--help" -o  $1 = "-h" ]
then
    usage
    exit 0
fi

# cd to the directory containing the deb `build` script
cd `dirname $0`

# function to automatically generate changelog
genchangelog()
{
    echo "$1 ($2) `lsb_release -sc`; urgency=low"
    echo
    prevtag=$(git describe --abbrev=0 HEAD^)
    git log --date=short --format="  * %s (%h, %cd)" "$prevtag"..HEAD |
            fold --spaces --width 76 | sed 's/^\([^ ]\+\)/    \1/'
    echo
    echo " -- $3  `LANG=C date -R`"
}

# generate package version from `git describe` and `lsb_release` info
pkgversion=$(git describe --dirty | cut -c2- |
             sed 's/-\([0-9]\+\)-\(g[0-9a-f]\+\)/+\1~\2/' |
             sed 's/\(~g[0-9a-f]\+\)-dirty$/-dirty\1/' |
             sed 's/-dirty/~dirty.'`date +%Y%m%d%H%M%S`'/'
            )-$(lsb_release -cs)

# get package maintainer info
pkgmaint=$(echo "`git config user.name` <`git config user.email`>")
description="Simple Asynchronous C API to MySQL databases"
url="https://github.com/sociomantic-tsunami/libdrizzle-redux"
vendor="Sociomantic Labs GmbH"
license="Simplified BSD License"

# the package name used in the distribution
pkgname=$1

# library .so name
so_libname=$pkgname.so

# relative path to the directory with library files to install
libdir="./install/usr/lib"

# get the ABI library version from the generated .so file
version_number=`find $libdir ! -type l -name "$so_libname.*"`
if [ ! -e $version_number ]; then
    echo "'.so' file not found"
    exit 1
fi

libversion=`echo $version_number | grep -o -P -e "([0-9]+\.?)+$"`
lib_major=$(echo $libversion | cut -f1 -d .)

# create temp file to write changelog to
changelog=`mktemp`
trap "rm -f '$changelog'; exit 1" INT TERM QUIT

# prepend the relative file path to so_libname
so_libname="$libdir/$so_libname"

# create a copy of the library file
cp $so_libname.$libversion $so_libname.$libversion.full

# strip symbols from the library file
strip $so_libname.$libversion

# libdrizzle-redux runtime package
genchangelog "$pkgname" "$pkgversion" "$pkgmaint" > "$changelog"
fpm -s dir -t deb -n "$pkgname" -v "$pkgversion" \
    --maintainer "$pkgmaint" \
    --description "$description" \
    --url "$url" \
    --vendor "$vendor" \
    --license "$license" \
    --category libs \
    --depends zlib1g \
    --depends libstdc++6 \
    --depends libc6 \
    --depends libgcc1 \
    --deb-changelog "$changelog" \
    --deb-no-default-config-files \
    $so_libname.$libversion=/usr/lib/ \
    $so_libname.$lib_major=/usr/lib/

# libdrizzle-redux debug package
genchangelog "$pkgname-dbg" "$pkgversion" "$pkgmaint" > "$changelog"
build_id=`readelf -n $so_libname.$libversion | \
    sed -n 's/^.*Build ID: \([a-f0-9]\{40\}\).*$/\1/p'`
debug_file=`echo $build_id | cut -b1-2`/`echo $build_id | cut -b3-`.debug
objcopy --only-keep-debug $so_libname.$libversion.full $so_libname.$libversion.debug
fpm -s dir -t deb -n "$pkgname-dbg" -v "$pkgversion" \
    --maintainer "$pkgmaint" \
    --description "$description" \
    --url "$url" \
    --vendor "$vendor" \
    --license "$license" \
    --category debug \
    --depends $pkgname \
    --deb-changelog "$changelog" \
    --deb-no-default-config-files \
    $so_libname.$libversion.debug=/usr/lib/debug/.build-id/$debug_file

# libdrizzle-redux development package
#
# the development headers are installed into a directory of the form:
#       /usr/include/libdrizzle-redux[MAJOR]/libdrizzle-redux
genchangelog "$pkgname-dev" "$pkgversion" "$pkgmaint" > "$changelog"
fpm -s dir -t deb -n "$pkgname-dev" -v "$pkgversion" \
    --maintainer "$pkgmaint" \
    --description "$description" \
    --url "$url" \
    --vendor "$vendor" \
    --license "$license" \
    --category libdevel \
    --depends $pkgname \
    --deb-changelog "$changelog" \
    --deb-no-default-config-files \
    install/usr/include/include/=/usr/include/$pkgname/ \
    $so_libname=/usr/lib/ \
    $libdir/$pkgname.a=/usr/lib/
