macro(INCLUDE_TEST test_name)
    add_executable(${test_name} ${test_name}.c)
    if (NOT BUILD_SHARED_LIBS)
        target_link_libraries(${test_name} drizzle-redux)
    else ()
        target_link_libraries(${test_name} drizzle-redux ${OPENSSL_LIBRARIES})
    endif ()
    add_test(${test_name} ${test_name})
endmacro(INCLUDE_TEST)
