#!/bin/sh
#
# script using fpm <https://github.com/jordansissel/fpm> to build libdrizzle-redux
# runtime, debugging and development deb packages
#
# Usage: ./build [api_level]
#
#     api_level        the api level for the package
#
# The `api_level` will be appended to the `package_name` for the generated
# packages, i.e. running `./build 6` would generate a packages named
# `libdrizzle-redux6`, `libdrizzle-redux6-dbg`, `libdrizzle-redux6-dev`.

set -e

# cd to the directory containing the deb `build` script
cd `dirname $0`

# function to automatically generate changelog
genchangelog()
{
    echo "$1 ($2) `lsb_release -sc`; urgency=low"
    echo
    prevtag=$(git describe --abbrev=0 HEAD^)
    git log --date=short --format="  * %s (%h, %cd)" "$prevtag"..HEAD |
            fold --spaces --width 76 | sed 's/^\([^ ]\+\)/    \1/'
    echo
    echo " -- $3  `LANG=C date -R`"
}

# generate package version from `git describe` and `lsb_release` info
pkgversion=$(git describe --dirty | cut -c2- |
             sed 's/-\([0-9]\+\)-\(g[0-9a-f]\+\)/+\1~\2/' |
             sed 's/\(~g[0-9a-f]\+\)-dirty$/-dirty\1/' |
             sed 's/-dirty/~dirty.'`date +%Y%m%d%H%M%S`'/'
            )-$(lsb_release -cs)

# get package maintainer info
pkgmaint=$(echo "`git config user.name` <`git config user.email`>")

# package name
pkgname=libdrizzle-redux

# library .so name
so_libname=$pkgname.so

# get the api level for the package from the cmd args
api_level=""
if [ $# -eq 1 -a ! -z "$1" ]; then
    api_level=$1
fi

# the package name used in the distribution
dist_pkgname=$pkgname$api_level

# the so library name used in the distribution
dist_so_libname=$dist_pkgname.so

# relative path to the directory with library files to install
libdir="./install/usr/lib"

# get the ABI library version from the generated .so file
version_number=`find $libdir ! -type l -name "$so_libname.*"`
if [ ! -e $version_number ]; then
    echo "'.so' file not found"
    exit 1
fi

libversion=`echo $version_number | grep -o -P -e "([0-9]+\.?)+$"`
lib_major=$(echo $libversion | cut -f1 -d .)

# create temp file to write changelog to
changelog=`mktemp`
trap "rm -f '$changelog'; exit 1" INT TERM QUIT

# (re)create symbolic links with the distributed package name, dist_pkgname
cd $libdir
touch $dist_so_libname.$libversion
ln -sf $dist_so_libname.$libversion $dist_so_libname.$lib_major
ln -sf $dist_so_libname.$lib_major $dist_so_libname
cd -

# prepend the relative file path to so_libname
so_libname="$libdir/$so_libname"

# create a copy of the library file
cp $so_libname.$libversion $so_libname.$libversion.full

# strip symbols from the library file
strip $so_libname.$libversion

# libdrizzle-redux runtime package
genchangelog "$dist_pkgname" "$pkgversion" "$pkgmaint" > "$changelog"
fpm -s dir -t deb -n "$dist_pkgname" -v "$pkgversion" \
    --architecture all \
    --maintainer "$pkgmaint" \
    --description "Simplified API to MySQL databases" \
    --url 'https://github.com/sociomantic-tsunami/libdrizzle-redux' \
    --vendor 'Sociomantic Labs GmbH' \
    --license 'Simplified BSD License' \
    --category libs \
    --depends zlib1g \
    --depends libstdc++6 \
    --depends libc6 \
    --depends libgcc1 \
    --deb-changelog "$changelog" \
    --deb-no-default-config-files \
    $so_libname.$libversion=/usr/lib/$dist_pkgname.so.$libversion \
    $libdir/$dist_so_libname.$lib_major=/usr/lib/

# libdrizzle-redux debug package
genchangelog "$dist_pkgname-dbg" "$pkgversion" "$pkgmaint" > "$changelog"
build_id=`readelf -n $so_libname.$libversion | \
    sed -n 's/^.*Build ID: \([a-f0-9]\{40\}\).*$/\1/p'`
debug_file=`echo $build_id | cut -b1-2`/`echo $build_id | cut -b3-`.debug
objcopy --only-keep-debug $so_libname.$libversion.full $so_libname.$libversion.debug
fpm -s dir -t deb -n "$dist_pkgname-dbg" -v "$pkgversion" \
    --architecture all \
    --maintainer "$pkgmaint" \
    --description "Simplified API to MySQL databases" \
    --url 'https://github.com/sociomantic-tsunami/libdrizzle-redux' \
    --vendor 'Sociomantic Labs GmbH' \
    --license 'Simplified BSD License' \
    --category debug \
    --depends $dist_pkgname \
    --deb-changelog "$changelog" \
    --deb-no-default-config-files \
    $so_libname.$libversion.debug=/usr/lib/debug/.build-id/$debug_file

# libdrizzle-redux development package
genchangelog "$dist_pkgname-dev" "$pkgversion" "$pkgmaint" > "$changelog"
fpm -s dir -t deb -n "$dist_pkgname-dev" -v "$pkgversion" \
    --architecture all \
    --maintainer "$pkgmaint" \
    --description "Simplified API to MySQL databases" \
    --url 'https://github.com/sociomantic-tsunami/libdrizzle-redux' \
    --vendor 'Sociomantic Labs GmbH' \
    --license 'Simplified BSD License' \
    --category libdevel \
    --depends $dist_pkgname \
    --deb-changelog "$changelog" \
    --deb-no-default-config-files \
    install/usr/include/include/=/usr/include/$pkgname/$dist_pkgname/ \
    $libdir/$dist_so_libname=/usr/lib/ \
    $libdir/$pkgname.a=/usr/lib/$dist_pkgname.a
